### ISSUE TITLE
Todo: drone.io

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/UHC-Reloaded#10]
As title.

**Comment by liach** [comment]
This idea is weird...

**Comment by 3TUSK** [comment]
That developer is yourself, haven't you realised?

**Comment by liach** [comment]
Actually I do not take care of the header but it would be really nice if you would like to integrate [travis-ci](https://travis-ci.org/) for this project. If you do so I will be glad and I will set up those required files. Note: Only project owners can change project settings and the integration is in project settings.

**Comment by 3TUSK** [comment]
Todo.
Probably I will return back to dev recently.
Btw, _Another project_ is actually _under-table_, meaning that none know the whole currently. Also there is actually no files.

**Comment by liach** [comment]
Somewhat I found that I forgot to tell you that you had better use GitLab or BitBucket in order to maintain private repositories. BitBucket limits your collaborators but GitLab doesn't.

**Comment by 3TUSK** [comment]
Suffering remembering too much passwords

**Comment by liach** [comment]
So now when will we use drone.io?

**Comment by 3TUSK** [comment]
<s>Hold on.</s> I'm doing something else... _huge challenge has been accepted and started._
Edit: realize that it's not very hard. see below for more info

**Comment by 3TUSK** [comment]
@liach Question: _Is_ [it](https://github.com/TinyModularThings/IC2Classic) compatible with IC2exp? I look at it roughly and they are _almost_ the same except `IEnergySourceInfo`.

**Comment by 3TUSK** [comment]
https://drone.io/github.com/3TUSK/UHC-Reloaded/files
I mean, if you have time, help me to set up it and close this issue. Thanks.

**Comment by liach** [comment]
??? You removed gradle wrapper... I will re-add it soon.

**Comment by 3TUSK** [comment]
Actually at first I didn't upload it.
<s>let me see if it work.</s> Edit: what.

**Comment by liach** [comment]
I've fixed and now we just need to wait.
Edit: It works... but I used `-i` and it got too much output.

**Comment by 3TUSK** [comment]
`error: CommandUhcTeam is not abstract and does not override abstract method compareTo(Object) in Comparable`
What.
(What happened in forge, i mean mcp)

**Comment by liach** [comment]
:imp:

**Comment by liach** [comment]
Fixed

**Comment by 3TUSK** [comment]
Finally. Cheer.
