### ISSUE TITLE
Further problem on ghast tear

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/UHC-Reloaded#2]
Not sure if the logic is suitable.
E.g.:
1.What if player has sword with looting III
2.What if some mod has their way to do the same effect as looting III, like focus in Thaumcraft 4

**Comment by liach** [comment]
I think you should make a class which is EntityGhast.java 's subclass and override the method "dropFewItems".

**Comment by 3TUSK** [comment]
@liach that is protected... then I didn't think further on that way

**Comment by liach** [comment]
Make a subclass "extends EntityGhast"...

**Comment by liach** [comment]
If it is still not available you can make coremods...

**Comment by 3TUSK** [comment]
@liach coremod is the best choice, but I really don't know how it wok.
btw, I am thinking if I can cancel the death of ghast...
