### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by liach** [3TUSK/UHC-Reloaded#3]
Use google codestyle?
http://google-styleguide.googlecode.com/svn/trunk/javaguide.html

**Comment by 3TUSK** [comment]
Hmmm... seems like I need to save time to read it.

**Comment by 3TUSK** [comment]
@liach also check this one if you are happy:
https://github.com/ExtraMeteorP/MeteorTech
Basically he is an op in a server, and I am in this server as well

**Comment by liach** [comment]
我被他的codestyle恶心了！

**Comment by 3TUSK** [comment]
@liach 我已经不忍看下去了……另外你好像退了TeamTF？

**Comment by liach** [comment]
Actually I'm not a member of TeamTF at all.. And I was once banned from the GregTech server hold by this organization because of griefing.. :sweat_smile:

**Comment by liach** [comment]
@3TUSK The package name should only contain low case letters. Please change "UHCReload" to "uhcreload".

**Comment by 3TUSK** [comment]
Will consider to do so today. Beside, I am working on asm... Hopefully I can solve some big problems via asm...
