### ISSUE TITLE
Package name should be all lower case

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/UHC-Reloaded#4]
As title shown. It will close as soon as all current packages get renamed.

**Comment by liach** [comment]
All files should be "UpperCamelCase", you should change "configHandler" to "ConfigHandler".

**Comment by 3TUSK** [comment]
Will change it as well.

**Comment by liach** [comment]
Actually "CommandUHCHelp" should be changed into "CommandUhcHelp". It's mentioned in the google java code style though.

**Comment by liach** [comment]
Nice!
