### ISSUE TITLE
Find a proper way to drop gold ingot from ghast

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/UHC-Reloaded#6]
WIP. I need to verify the validity of my code.

**Comment by liach** [comment]
Actually ASM is dangerous. This will break compatibility. We just need a subclass to 

``` java
@Override
```

**Comment by 3TUSK** [comment]
Override?
I have no idea of its usage... I mean I don't know how to use override to replace that.

**Comment by liach** [comment]
This allows a method to replace the method in its super class. I suggest you to have a look at https://github.com/3TUSK/UHC-Reload/blob/master/src/main/java/mod/uhcreloaded/commands/CommandUhcHelp.java
That uses `@Override` to prevent the methods' output from being replaced by the method in original CommandBase.java file.

**Comment by 3TUSK** [comment]
The problem is, after override, where should I register it, or what should I do, to apply the new, overrided method so that the original one can be replaced? That is what I cannot figure out currently.

**Comment by liach** [comment]
Or can you remove the brewing recipe of the tear and add the recipe to get gold from tears?

**Comment by 3TUSK** [comment]
Sounds okay, but not exactly catch the rule of UHC.
I will think more about it.

**Comment by liach** [comment]
Um.. I want to improve compatibility for mods though.
