### ISSUE TITLE
Future Ideas

### ISSUE THREAD

**Issue by liach** [3TUSK/UHC-Reloaded#8]
Here I listed some ideas that might be applicable.
- [ ] support teams
- [ ] Generate a UHC world using existing `WorldProvider`s, like TwilightForest world.
  - [ ] Custom or Random worlds
  - [ ] Support nether & end
- [ ] Make the "Player Skull", which is an Golden Apple now, into a real Player Skull with effect and should be eatable.
  - [x] Add player name on the golden apple. (Actually done)
- [ ] World Border support for UHC Worlds.
- [x] ~~Make it a mod that could be not required on client when installed on server, like ForgeEssentials.(be3258fb86410ba09cdd2a7c5d2ce601e75879e4)~~
- [ ] ~~Support [ForgeEssentials](https://github.com/ForgeEssentials/ForgeEssentialsMain) (When ForgeEssentials has moved to 1.8)~~
  Note: Should not really support fe since its code is messy.

> - [ ] Configurable players per team (1 for individual)
> - [ ] Health in tab
> - [ ] Lobby
> - [ ] Compass tracker
> - [ ] Custom WorldRadius (Auto reducing, etc..)
> - [ ] No hunger until PVP
> - [ ] Disable PVP time
> - [ ] Deathmatch (With custom world)
> - [ ] Chat formats (Team, Global, Death)
> - [ ] Team in tab
> - [ ] Configurable messages
> - [ ] Game status server motds
> - [ ] NO player limit & NO players per team limit
> - [ ] Scoreboard (Time, Teams left, WorldBorder, Teammates…)
> - [ ] Spectator mode included (Compass, return to lobby…)
> - [ ] Kits
> - [ ] Perms:
> - [ ] uhckits.<kitname>
> - [ ] Death chat
> - [ ] Chat per team (@ or ! for global, if you have it activated)
> - [ ] Disable commands during game
> - [ ] Attractive messages and sounds
> - [ ] 1.8 Titles & action bars
> - [ ] Safe time when disconnect (Configurable time)
> - [ ] Disable chat in lobby
> - [ ] Min players to start game & countdown
> - [ ] Prevent build in lobby
> - [ ] Disallow spectate
> - [ ] 1.8 Spectator gamemode
> - [ ] 1.8 Spectator night vision
> - [ ] Team prefixes in tags
> - [ ] Kick to specific lobby server
> - [ ] Teammates status, distance, & health
> - [ ] Reward commands for winners
> - [ ] Reward commands on kill

**Comment by liach** [comment]
Bookmark: http://www.spigotmc.org/resources/fully-automated-ultra-hardcore-auto-uhc.1911/

**Comment by liach** [comment]
@3TUSK Could you rename the repo to `UHC-Reloaded`? This's a bit confusing.

**Comment by 3TUSK** [comment]
Will rename today.
getCurrentStatus(3TUSK)==busy

**Comment by 3TUSK** [comment]
Should we add command /team or just use the vanilla scordboard?
Also, http://forum.feed-the-beast.com/threads/whats-new-in-modded-minecraft-today.39595/page-479#post-1253142
- [ ] /team and other commands

**Comment by liach** [comment]
What does that link mean? New brewing registry system?

**Comment by liach** [comment]
> Configurable players per team (1 for individual)
- Health in tab
Spoiler: Image
- Lobby
- Support teams!
Spoiler: Image
- Custom or Random worlds
- Support nether & end
- Compass tracker
- Custom WorldRadius (Auto reducing, etc..)
- No hunger until PVP
- Disable PVP time
- Deathmatch (With custom world)
- Chat formats (Team, Global, Death)
Spoiler: Image
- Team in tab (1.8)
- Configurable messages
- Game status server motds
Spoiler: Image
- NO player limit & NO players per team limit
- Scoreboard (Time, Teams left, WorldBorder, Teammates…)
Spoiler: Images
- Special crafts:
Spoiler: Images
 Spoiler: Images
- Spectator mode included (Compass, return to lobby…)
Spoiler: Image
- Kits
- Perms:
- uhckits.<kitname>
Spoiler: Kits
- Death chat
- Chat per team (@ or ! for global, if you have it activated)
- Disable commands during game
- Attractive messages and sounds
- 1.8 Titles & action bars
- Safe time when disconnect (Configurable time)
- Disable chat in lobby
- Min players to start game & countdown
- Prevent build in lobby
- Disallow spectate
- 1.8 Spectator gamemode
- 1.8 Spectator night vision
- Team prefixes in tags
- Support GroupManager
- Support PermissionsEx
- Kick to specific lobby server
- Teammates status, distance, & health
- Reward commands for winners
- Reward commands on kill
- And more…

**Comment by 3TUSK** [comment]
Sorry for ambiguous. 
Seems that we can make a new team system.

> New ability to add prefix and suffixes to player's display na,e.

**Comment by liach** [comment]
Ok team next

**Comment by liach** [comment]
@3TUSK You will not work on this mod recently, right? I'd move them to the readme.

**Comment by 3TUSK** [comment]
Yep. Study is more important, isn't it?
Thanks for contribution.

**Comment by liach** [comment]
Btw have you finished your final

**Comment by 3TUSK** [comment]
Finished at the end of May. Now I am studying for SAT.

**Comment by liach** [comment]
how about act...

**Comment by 3TUSK** [comment]
Currently whether act is needed is still unknown...

**Comment by liach** [comment]
Moved to [here](https://github.com/3TUSK/UHC-Reloaded/wiki/Future-Plan) now.

**Comment by 3TUSK** [comment]
@liach Probably I don't have enough time to continue this mod... Do you have any interest?

**Comment by liach** [comment]
Yes but somehow I lost collaborator access because I accidentally blocked you... I would like to accept this project and make it into a Forge mod for 1.9 and a sponge plugin(Sponge plugins are fun).

**Comment by 3TUSK** [comment]
Gonna to transfer ownership tomorrow… I HAVE TO go to sleep right now…………

**Comment by liach** [comment]
Me too...

**Comment by liach** [comment]
@3TUSK Would you allow me to change the license to MIT?

**Comment by 3TUSK** [comment]
I permit the permission of re-licensing UHC-Reloaded to MIT to you. 

Make a good use!

**Comment by liach** [comment]
Thanks!
